services:
  mongo:
    image: mongo:6
    container_name: opsai_mongo
    ports: ["27017:27017"]
    volumes:
      - mongo_data:/data/db
  redis:
    image: redis:7
    container_name: opsai_redis
    ports: ["6379:6379"]
  qdrant:
    image: qdrant/qdrant:latest
    container_name: opsai_qdrant
    ports: ["6333:6333", "6334:6334"]
    volumes:
      - qdrant_data:/qdrant/storage
volumes:
  mongo_data:
  qdrant_data:
